// can also be named as config.js

export const IMG_CDN_URL =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_MENU_URL =
	"https://www.swiggy.com/dapi/menu/v4/full?lat=28.6712458&lng=77.3176541&menuId=";
export const restaurantList = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "93981",
			name: "Subway",
			uuid: "50935f24-ecfb-4cdc-98fb-39365e9808fd",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "oveqql4umeu8cqtzaanx",
			cuisines: ["Fast Food", "Salads", "Snacks", "Desserts", "Beverages"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 31,
			minDeliveryTime: 31,
			maxDeliveryTime: 31,
			slaString: "31 MINS",
			lastMileTravel: 3.700000047683716,
			slugs: {
				restaurant: "subway-karkardooma-dilshad-gardens-2",
				city: "delhi",
			},
			cityState: "4",
			address:
				"No-12, Ground Floor, Hargobin Enclave, Delhi-110092 Opposite Metro Pillar 118, Karkardooma, New Delhi",
			locality: "Karkardooma",
			parentId: 2,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5792520~p=1~eid=00000185-faba-8c96-1f0c-c8f800ef011d",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "93981",
				deliveryTime: 31,
				minDeliveryTime: 31,
				maxDeliveryTime: 31,
				lastMileTravel: 3.700000047683716,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.0",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "170351",
			name: "Guru Nanak Rasoi",
			uuid: "68e556b5-06e1-4fef-8b1b-fae8474bfa93",
			city: "4",
			area: "Dilshad Garden",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "qofygsjfssx9hpbm6s18",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: "23 MINS",
			lastMileTravel: 1.5,
			slugs: {
				restaurant: "guru-nanak-rasoi-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Shop 3, Block-A, Near Hari Wardi Government School, Dilshad Garden, New Delhi",
			locality: "Near Hari Wardi",
			parentId: 277425,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "170351",
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 1.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.7",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "562100",
			name: "Pizza the hunger choice",
			uuid: "8951cfd5-b653-4deb-8e9f-b3b461eda416",
			city: "4",
			area: "PREET VIHAR",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "effhrgouce2ckjky54lx",
			cuisines: ["Pizzas", "Chinese", "Fast Food", "Snacks", "Beverages"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: "28 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "pizza-the-hunger-choice-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, Vishwakarma Nagar, Jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Dilshad Gardens",
			parentId: 252753,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "562100",
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "563215",
			name: "PIZZA BITE",
			uuid: "3941413e-231f-4ee8-8db7-a6dfb01a0e92",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "fqf3d6phexihuw7n9wp2",
			cuisines: ["Pizzas", "North Indian", "Chinese", "Fast Food"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: "27 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "pizza.bite-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, Vishwakarma Nagar, Jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Preet Vihar",
			parentId: 158349,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "563215",
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "571441",
			name: "Pizza Delight",
			uuid: "b894188d-c102-4cb4-9b45-30f567d71df5",
			city: "4",
			area: "Pratap khand",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "upltzvqwbptjlxinfeys",
			cuisines: ["Pizzas"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 30,
			minDeliveryTime: 30,
			maxDeliveryTime: 30,
			slaString: "30 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "pizzadelicious-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, vishwakarma nagar, jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Pratap khand",
			parentId: 158500,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "571441",
				deliveryTime: 30,
				minDeliveryTime: 30,
				maxDeliveryTime: 30,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "616593",
			name: "Love At First Bite",
			uuid: "c9c46869-9fc6-45dd-b764-a706e5cbe521",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "qigfoguvu4ojjqtcx0vp",
			cuisines: ["Bakery"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: "25 MINS",
			lastMileTravel: 1.2000000476837158,
			slugs: {
				restaurant: "love-at-first-bite-dilshad-gardens-dilshad-gardens-3",
				city: "delhi",
			},
			cityState: "4",
			address:
				"The New Shop, 488/5-A, GF, Plot No-E-1, Near MCD Primary School, SEEMA PURI, Shahdara, Delhi-110095",
			locality: "Seemapuri",
			parentId: 249582,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "616593",
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 1.2000000476837158,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "616594",
			name: "Tongue twisters",
			uuid: "badbb471-7716-402d-9af1-ddc962b6af35",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "lz955a1j5fzq5riiehdv",
			cuisines: ["Ice Cream", "Beverages"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 1.2000000476837158,
			slugs: {
				restaurant: "tongue-twisters-dilshad-gardens-dilshad-gardens-4",
				city: "delhi",
			},
			cityState: "4",
			address:
				"The New Shop, 488/5-A, GF, Plot No-E-1, Near MCD Primary School, SEEMA PURI, Shahdara, Delhi-110095",
			locality: "Seemapuri",
			parentId: 2728,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "616594",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 1.2000000476837158,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "562095",
			name: "Italian pizza king",
			uuid: "51ea2ab4-17ac-47f3-bb7d-f98e6a5ef812",
			city: "4",
			area: "PREET VIHAR",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "nrtd6iz2surofgvnoten",
			cuisines: ["Pizzas", "Chinese", "Fast Food", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "italian-pizza-king-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, Vishwakarma Nagar, Jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Dilshad Gardens",
			parentId: 107594,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "562095",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.4",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "617459",
			name: "PIZZA SINGH",
			uuid: "46a804d5-1dc5-4bea-a417-613ea13ef2b1",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "pz22jtxjvfyfc9klebbg",
			cuisines: ["Italian", "Fast Food", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "pizza-singh-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"ground floor,a 57,Block A, Jhilmil Colony, Delhi, 110095, India",
			locality: "Jhilmil Colony",
			parentId: 158937,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "617459",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "5.0",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "571497",
			name: "Shake theka",
			uuid: "cc7d8909-3232-4e23-9b61-7a989684a305",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "yhnbaqc5mj0fxxf9wljs",
			cuisines: ["Pizzas", "Burgers", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "shake-theka-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, vishwakarma nagar, jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Pratap Khand",
			parentId: 343064,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "571497",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.6",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "152953",
			name: "Burger Singh (Big Punjabi Burgers)",
			uuid: "63cd24b5-b30e-43ba-bfcf-cf33a6ef2660",
			city: "4",
			area: "Krishna Nagar",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "hmloyebpeieeyqcsfowr",
			cuisines: ["American", "Fast Food", "Snacks"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 30,
			minDeliveryTime: 30,
			maxDeliveryTime: 30,
			slaString: "30 MINS",
			lastMileTravel: 4.199999809265137,
			slugs: {
				restaurant: "burger-singh-laxmi-nagar",
				city: "delhi",
			},
			cityState: "4",
			address: "Plot No. 3, Block - D, Krishna Nagar - 110051",
			locality: "Krishna Nagar",
			parentId: 375065,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "152953",
				deliveryTime: 30,
				minDeliveryTime: 30,
				maxDeliveryTime: 30,
				lastMileTravel: 4.199999809265137,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "617457",
			name: "Royals Pizza",
			uuid: "8c94454a-8d27-471f-b7c4-c6b7532aa173",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "tl9ey8ryzpztotfl9nh3",
			cuisines: ["Pizzas", "Beverages"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 21,
			minDeliveryTime: 21,
			maxDeliveryTime: 21,
			slaString: "21 MINS",
			lastMileTravel: 1.7999999523162842,
			slugs: {
				restaurant: "royals-pizza-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"11, Pratap khand, Vishwakarma Nagar, Jhilmil, Delhi -110095, PREET VIHAR, East , , Delhi, 110095",
			locality: "Preet Vihar",
			parentId: 232651,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "617457",
				deliveryTime: 21,
				minDeliveryTime: 21,
				maxDeliveryTime: 21,
				lastMileTravel: 1.7999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "558180",
			name: "Urban Tapri",
			uuid: "87bb8ff6-e19a-4f78-93cd-67fade6bdf7d",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "lprqmeq9hyp87o7izffs",
			cuisines: ["Beverages", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 2.299999952316284,
			slugs: {
				restaurant: "urban-tapri-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"The New Shop, F-7, Ground Floor, Dilshad Colony, Dilshad Garden, SHAHDARA, Shahdara, Delhi-110095",
			locality: "Seemapuri Road",
			parentId: 220172,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "558180",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 2.299999952316284,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "558188",
			name: "Takeout Cafe",
			uuid: "81f8857c-939e-4d88-8b00-429c403253d4",
			city: "4",
			area: "Dilshad Gardens",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "qvalkf9nqmwrdyzftbd4",
			cuisines: ["Cafe", "Fast Food", "Snacks", "Chinese"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 2.299999952316284,
			slugs: {
				restaurant: "takeout-cafe-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"The New Shop, F-7, Ground Floor, Dilshad Colony, Dilshad Garden, SHAHDARA, Shahdara, Delhi-110095",
			locality: "Shahdara",
			parentId: 293626,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "558188",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 2.299999952316284,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "311241",
			name: "Momos Hub",
			uuid: "98d79c54-93f8-4e9f-9be0-594f4b7adf77",
			city: "4",
			area: "Dilshad Garden",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "tg9p7ub2qdksh4vkziwf",
			cuisines: ["Chinese", "Indian"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 2.5,
			slugs: {
				restaurant: "momo-hub-dilshad-gardens-dilshad-gardens",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Add A.453 old seemapuri delhi 95, MANDOLI, SEEMA PURI, Shahdara, Delhi, 110095",
			locality: "Seemapuri",
			parentId: 138385,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "311241",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 2.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
];
